version: "3.9"
services:
        mysqldb:
                image: mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=123
                        - MYSQL_DATABASE=seenit
                volumes:
                        - seenitdb:/var/lib/mysql
       
        client:
                image: seenit-client
                build: 
                        context: ./client
                        args: 
                         - REACT_APP_API_BASE_URL=http://server:8080
                ports: 
                        - "5050:80"
                restart: always
                depends_on:
                        - server

        server:
                image: seenit-server
                build: ./server
                ports:
                        - "8081:8080"
                restart: always
                depends_on:
                        - mysqldb
                environment:
                        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/seenit?allowPublicKeyRetrieval=true&useSSL=false
volumes:
        seenitdb:
